name: Prueba envio correo
on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar correo
        uses: ErickDarkFire/Practica2@main
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Push en rama ${{ github.ref_name }}"
          to: "erickrodriguezgomez04@gmail.com"
          from: "Erick"
          body: "Se realizó un push en la rama: ${{ github.ref_name }}"
